// khi load sẽ load layout trước rồi mới load page
// @/ là ở src
// nó được config ở tsconfig.json
import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
// nhúng styles chung
import '@/styles/globals.css'
import Header from '@/components/Header'
// import những base chung
import '@/styles/index.scss';
import SideBar from '@/components/Sidebar';
const inter = Quicksand({ subsets: ['latin'] })
import 'react-rangeslider/lib/index.css';
import ProductCard from '@/components/ProductCard';
import Footer from '@/components/Footer';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col h-screen w-screen'>
          <Header />
          <div className='flex-1 overflow-y-auto bg-white'>
            <main className="min-h-[130rem] flex flex-col max-w-screen-xl m-auto">
              {children}
            </main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
